- hosts: all
  become: true
  gather_facts: False
  tasks:
   - name: Install python3
     apt:
       name: python3
       update_cache: yes

   - name: Install pip3
     apt:
       name: python3-pip
       update_cache: yes
