---
- hosts: all
  become: yes
  vars:
    NORMAL_USER_NAME: 'ansible'
  tasks:
    - name: "Create Ansible User"
      user: name={{ NORMAL_USER_NAME }}
            password='$6$rounds=656000$s/kwRajksbvLb7bk$PK.TIsuHzyi6/FveE/CpAzWW8Kvp452gxOIxtND5p2i0QN9eWNZzemrsAazYl88uanejy9JfyOdh.lVw9Rhzs1'
            shell=/bin/bash

    - name: Add remote authorized key to allow future passwordless logins
      authorized_key: user={{ NORMAL_USER_NAME }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Add Ansible user to sudoers
      lineinfile: dest=/etc/sudoers
                  regexp="{{ NORMAL_USER_NAME }} ALL"
                  line="{{ NORMAL_USER_NAME }} ALL=(ALL) NOPASSWD:ALL"
                  state=present
